#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v19
# autospec commit: 6a4b23bb3e69
#
Name     : azure-c-logging
Version  : a815415ea2c48e5f0d9c58b58228264837c8beea
Release  : 1
URL      : https://github.com/Azure/c-logging/archive/a815415ea2c48e5f0d9c58b58228264837c8beea/azure-c-logging-a815415ea2c48e5f0d9c58b58228264837c8beea.tar.gz
Source0  : https://github.com/Azure/c-logging/archive/a815415ea2c48e5f0d9c58b58228264837c8beea/azure-c-logging-a815415ea2c48e5f0d9c58b58228264837c8beea.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: azure-c-logging-license = %{version}-%{release}
BuildRequires : azure-macro-utils-c-dev
BuildRequires : buildreq-cmake
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Fix-broken-cmake.patch

%description
# Contributing
This project welcomes contributions and suggestions.  Most contributions require you to agree to a
Contributor License Agreement (CLA) declaring that you have the right to, and actually do, grant us
the rights to use your contribution. For details, visit https://cla.opensource.microsoft.com.

%package dev
Summary: dev components for the azure-c-logging package.
Group: Development
Provides: azure-c-logging-devel = %{version}-%{release}
Requires: azure-c-logging = %{version}-%{release}

%description dev
dev components for the azure-c-logging package.


%package license
Summary: license components for the azure-c-logging package.
Group: Default

%description license
license components for the azure-c-logging package.


%prep
%setup -q -n c-logging-a815415ea2c48e5f0d9c58b58228264837c8beea
cd %{_builddir}/c-logging-a815415ea2c48e5f0d9c58b58228264837c8beea
%patch -P 1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1726272541
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1726272541
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/azure-c-logging
cp %{_builddir}/c-logging-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/azure-c-logging/5c8d40f5ba076a94ba059fd1c53ad3b1e261e164 || :
export GOAMD64=v2
GOAMD64=v2
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/c_logging/consolelogger.h
/usr/include/c_logging/logging_stacktrace.h
/usr/include/c_logging/v2/c_logging/log_context.h
/usr/include/c_logging/v2/c_logging/log_context_property_basic_types.h
/usr/include/c_logging/v2/c_logging/log_context_property_bool_type.h
/usr/include/c_logging/v2/c_logging/log_context_property_to_string.h
/usr/include/c_logging/v2/c_logging/log_context_property_type.h
/usr/include/c_logging/v2/c_logging/log_context_property_type_ascii_char_ptr.h
/usr/include/c_logging/v2/c_logging/log_context_property_type_if.h
/usr/include/c_logging/v2/c_logging/log_context_property_type_struct.h
/usr/include/c_logging/v2/c_logging/log_context_property_type_wchar_t_ptr.h
/usr/include/c_logging/v2/c_logging/log_context_property_value_pair.h
/usr/include/c_logging/v2/c_logging/log_errno.h
/usr/include/c_logging/v2/c_logging/log_internal_error.h
/usr/include/c_logging/v2/c_logging/log_level.h
/usr/include/c_logging/v2/c_logging/log_sink_callback.h
/usr/include/c_logging/v2/c_logging/log_sink_console.h
/usr/include/c_logging/v2/c_logging/log_sink_if.h
/usr/include/c_logging/v2/c_logging/logger.h
/usr/include/c_logging/v2/c_logging/logger_v1_v2.h
/usr/include/c_logging/xlogging.h

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/azure-c-logging/5c8d40f5ba076a94ba059fd1c53ad3b1e261e164
